### PR TITLE
replace ustring with runes

### PR DESCRIPTION
**Pull request by danieldaeschle**
Needs to be tested. It compiles but I can't test the UI.

### CODE REVIEW

**Comment by spytheman** [comment]
Before this PR:
image

After this PR:
image

**Comment by spytheman** [comment]
I think the problem is that this:
```v
x := 'abcde'
ux := x.ustring()
rx := x.runes()
dump(x)
dump(rx)
dump(ux.substr(0, 2).str())
dump(rx[0..2])
```
produces:
```
[x.v:4] x: abcde
[x.v:5] rx: [`a`, `b`, `c`, `d`, `e`]
[x.v:6] ux.substr(0, 2).str(): ab
[x.v:7] rx[0 .. 2]: [`a`, `b`]
```

**Comment by danieldaeschle** [comment]
yeah, i thought this would happen. I need to add .string() somewhere where it's needed.

**Comment by danieldaeschle** [comment]
Could you test it again?

**Comment by spytheman** [comment]
You need also:
image

Now, it renders properly after inserting text, but the new text is limited to the size of the old line, i.e. it behaves somewhat like replacing the characters, instead of inserting new ones and shifting the remaining to the right.

**Comment by spytheman** [comment]
Perhaps there is a off by 1 error in slicing during the insertion somewhere 🤔 .

**Comment by spytheman** [comment]
Yep, it needs this too:
image

**Comment by spytheman** [comment]
Sorry for not pushing commits directly, but I do not have permissions to merge here, so I can not also modify your branch 🤷🏻‍♂️ .

**Comment by medvednikov** [comment]
seems to work fine, didn't find any issues

good job!

**Pull request merged**
